import {archipelago,checker} from './samples.mjs';
const $=id=>document.getElementById(id);let sample=archipelago,worker,timer,output;
function draw(canvas,image){canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d'),data=context.createImageData(image.width,image.height);for(let i=0;i<image.pixels.length;i++){const c=image.pixels[i],p=i*4;data.data[p]=c>>>16&255;data.data[p+1]=c>>>8&255;data.data[p+2]=c&255;data.data[p+3]=c>>>24}context.putImageData(data,0,0)}
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':''}
function stop(){if(worker){worker.terminate();worker=undefined}clearTimeout(timer);$('cancel').disabled=true;$('generate').disabled=false;$('run-json').disabled=false;$('stage').classList.remove('busy')}
function select(value){stop();$('save').disabled=true;output=undefined;status('样本已选择，点击生成图案。');sample=value;draw($('sample'),sample);$('sample-name').textContent=sample.name+' · '+sample.width+' × '+sample.height;if(value===checker)$('size').value='2';updateJob()}
function parameters(){return {mode:'overlap',sample:sample.pixels,sampleWidth:sample.width,sampleHeight:sample.height,size:Number($('size').value),width:Number($('width').value),height:Number($('height').value),seed:Number($('seed').value),symmetry:$('symmetry').checked?8:1,periodicInput:$('periodic-input').checked,periodic:$('periodic').checked,budget:30000000}}
function updateJob(){$('job').value=JSON.stringify(parameters())}
function execute(job){stop();const start=performance.now();worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});$('generate').disabled=true;$('run-json').disabled=true;$('cancel').disabled=false;$('stage').classList.add('busy');$('save').disabled=true;status('正在生成…');
 timer=setTimeout(()=>{stop();status('生成超时，请减小尺寸或调整样本。',true)},30000);
 worker.onerror=event=>{stop();status('生成失败：'+event.message,true)};
 worker.onmessage=event=>{stop();const result=event.data;$('json-result').textContent=JSON.stringify({...result,pixels:result.pixels?'['+result.pixels.length+' 个像素]':undefined},null,2);if(!result.ok){status('生成失败：'+result.error,true);return}if(result.status==='unsat'){status('当前约束无解，请调整尺寸、周期或样本。',true);return}if(result.pixels){output=result;draw($('result'),result);$('save').disabled=false;status(result.width+' × '+result.height+' · '+(result.patternCount??result.solution?.decisions??0)+' 个图案 / 决策 · '+Math.round(performance.now()-start)+' ms')}else status('模型检查完成 · '+Math.round(performance.now()-start)+' ms')};worker.postMessage(job)
}
$('island').onclick=()=>select(archipelago);$('checker').onclick=()=>select(checker);$('generate').onclick=()=>{updateJob();execute(parameters())};$('cancel').onclick=()=>{stop();status('已取消生成。')};$('run-json').onclick=()=>{try{execute(JSON.parse($('job').value))}catch(error){status('JSON 错误：'+error.message,true)}};
for(const id of ['width','height','size','seed','symmetry','periodic-input','periodic'])$(id).addEventListener('change',updateJob);
$('upload').onchange=async()=>{try{const file=$('upload').files[0];if(!file)return;if(file.size>16777216)throw Error('PNG 不能超过 16 MiB');const head=new DataView(await file.slice(0,24).arrayBuffer());if(head.byteLength<24||head.getUint32(0)!==0x89504e47||head.getUint32(4)!==0x0d0a1a0a)throw Error('请选择 PNG');const w=head.getUint32(16),h=head.getUint32(20);if(!w||!h||w*h>262144)throw Error('样本最多 262144 像素');const bitmap=await createImageBitmap(file,{colorSpaceConversion:'none',premultiplyAlpha:'none'});const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0);bitmap.close();const data=ctx.getImageData(0,0,w,h).data,pixels=Array.from({length:w*h},(_,i)=>(data[i*4+3]<<24)|(data[i*4]<<16)|(data[i*4+1]<<8)|data[i*4+2]);select({name:file.name,width:w,height:h,pixels});status('样本已导入。')}catch(error){status(error.message,true)}};
$('save').onclick=()=>{if(!output)return;$('result').toBlob(blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='wfc-'+output.width+'x'+output.height+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')};
select(archipelago);execute(parameters());
